### ISSUE TITLE
Still having problem connecting to cassandra

### ISSUE THREAD

**Issue by topiaruss** [simplyzaki/docker-images#2]
Hi Zaki,
I'm trying to get cqlengine (https://github.com/cqlengine/cqlengine) to connect to cassandra.

Here is my test:
https://github.com/gremlins/shipyard/blob/master/initial_tests/initial_tests/test.py

With or without username/password on lines 16-17, I get what looks like a password issue during connect:

```
$ python test.py
Traceback (most recent call last):
  File "test.py", line 22, in <module>
    sync_table(ExampleModel)
  File "/home/vagrant/shipyard/initial_tests/local/lib/python2.7/site-packages/cqlengine/management.py", line 73, in sync_table
    create_keyspace(ks_name)
  File "/home/vagrant/shipyard/initial_tests/local/lib/python2.7/site-packages/cqlengine/management.py", line 31, in create_keyspace
    _, keyspaces = con.execute("""SELECT keyspace_name FROM system.schema_keyspaces""", {})
  File "/home/vagrant/shipyard/initial_tests/local/lib/python2.7/site-packages/cqlengine/connection.py", line 222, in execute
    raise CQLEngineException("Could not execute query against the cluster")
cqlengine.exceptions.CQLEngineException: Could not execute query against the cluster
(initial_tests)vagrant@precise64:~/shipyard/initial_tests/initial_tests$
```

I'm assuming that the default cassandra username and password apply.

I also suspect that contrary to your doc, the ubuntu password on the Docker image may be other than ubuntu.

Best regards,

--r

**Comment by simplyzaki** [comment]
Couldn't get time to look at this, due to my current travel plans. Once back to desk, will check and get back. Hope this helps.

**Comment by topiaruss** [comment]
No, that's absolutely fine. I have also had to take a few days on some other tasks. This is on my list of things to look at in the coming days, so any comments in the meantime would be very helpful.

My initial thought was to put the test code that I am currently running outside the docker container,  inside the container to see if it's able to connect there. Do I get the same connection issue? It's possible that I'm having permissions problems, but I rather doubt it. Anyway... I do have a path to start diagnosing, and will provide any information I can as soon as I get back to it.

Best regards,

--r.

On 12 Nov 2013, at 10:20, Zakiullah Khan Mohammed notifications@github.com wrote:

> Couldn't get time to look at this, due to my current travel plans. Once back to desk, will check and get back. Hope this helps.
> 
> —
> Reply to this email directly or view it on GitHub.

Russ Ferriday -- Software and Systems Architect/Developer
CEO Topia Systems Ltd.
russf@topia.com  --  +44 7429 518822  --  www.topia.com

**Comment by topiaruss** [comment]
The account & password for ssh is root & root

**Comment by simplyzaki** [comment]
Yes.

**Comment by simplyzaki** [comment]
@topiaruss It seems to be a problem with netmasking the container's IP address, try pipework to resolve this issue.

**Comment by kivo360** [comment]
Did anybody happen to figure out this issue? I'm having the problem while testing ways to distribute my data.
